### ISSUE TITLE
タスクの期限を空にして登録した時、0000-00-00と表示される。

### ISSUE THREAD

**Issue by zenpou** [MOS09/PHP-Todolist#4]
https://blooming-ocean-46381.herokuapp.com/index.php
で、タスクを登録する際、期限を空欄のまま登録すると
該当のタスクの日付表示が0000-00-00と出力されます。

非表示にするか、未設定などと表示するとわかりやすいと思います。

**Comment by mos0917** [comment]
現最新のコミットにて修正済みです。
タスク登録時にnullにして登録した場合、タスク編集モーダルにてnullにした場合ともに修正しています。
